// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgsxivotekaxeustofls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhnc3hpdm90ZWtheGV1c3RvZmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTEzNDUsImV4cCI6MjA2NTUyNzM0NX0.Rm15tslHv8k8uuSQpmBtKH90oB3h9ZVWbCq3-VDe1Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);